services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopsmart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/shopsmart
      REDIS_LOCAL_URL: redis://redis:6379
      NODE_ENV: production
      FRONTEND_LOCAL_URL: http://localhost:3000
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_LOCAL_BACKEND_URL: http://localhost:5001/api
      NODE_ENV: production
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: